# Wazuh App Copyright (C) 2021 Wazuh Inc. (License GPLv2)
version: '3.7'

services:
  wazuh:
    image: wazuh/wazuh-odfe:4.2.5
    hostname: wazuh-manager
    container_name: wazuh-manager
    restart: always
    cpus: 1.0
    mem_limit: 2g
    networks:
      wazuh:
        ipv4_address: 10.0.1.5
    ports:
      - "1514:1514"
      - "1515:1515"
      - "514:514/udp"
      - "55000:55000"
    env_file:
      - ".env"
    environment:
      - ELASTICSEARCH_URL=https://elasticsearch:9200
      - ELASTIC_USERNAME=admin
      - ELASTIC_PASSWORD=$ELASTIC_ADMIN_PASS
      - FILEBEAT_SSL_VERIFICATION_MODE=full
      - SSL_CERTIFICATE_AUTHORITIES=/etc/ssl/root-ca.pem
      - SSL_CERTIFICATE=/etc/ssl/filebeat.pem
      - SSL_KEY=/etc/ssl/filebeat.key
      - API_USERNAME=wazuh-api
      - API_PASSWORD=$WAZUH_API_PASS
    volumes:
      - /data/wazuh/manager/ossec:/var/ossec
      - /data/wazuh/manager/filebeat/etc:/etc/filebeat
      - /data/wazuh/manager/filebeat/var:/var/lib/filebeat
      - /data/wazuh/manager/wazuh_manager.conf:/wazuh-config-mount/etc/ossec.conf
      - ./ssl_certs/root-ca.pem:/etc/ssl/root-ca.pem
      - ./ssl_certs/filebeat.pem:/etc/ssl/filebeat.pem
      - ./ssl_certs/filebeat.key:/etc/ssl/filebeat.key
  
  es01:
    image: amazon/opendistro-for-elasticsearch:1.13.2
    hostname: es01
    container_name: es01
    restart: always
    cpus: 1.0
    mem_limit: 4g
    networks:
      wazuh:
        ipv4_address: 10.0.1.11
        aliases: 
          - elasticsearch
    ports:
      - "9200:9200"
    environment:
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - /data/elastic/es01:/usr/share/elasticsearch/data
      - ./production_cluster/ssl_certs/root-ca.pem:/usr/share/elasticsearch/config/root-ca.pem
      - ./production_cluster/ssl_certs/es01.key:/usr/share/elasticsearch/config/es01.key
      - ./production_cluster/ssl_certs/es01.pem:/usr/share/elasticsearch/config/es01.pem
      - ./production_cluster/ssl_certs/admin.pem:/usr/share/elasticsearch/config/admin.pem
      - ./production_cluster/ssl_certs/admin.key:/usr/share/elasticsearch/config/admin.key
      - ./production_cluster/elastic_conf/es01.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./production_cluster/elastic_conf/internal_users.yml:/usr/share/elasticsearch/plugins/opendistro_security/securityconfig/internal_users.yml

  es02:
    image: amazon/opendistro-for-elasticsearch:1.13.2
    hostname: es02
    container_name: es02
    restart: always
    cpus: 1.0
    mem_limit: 4g
    networks:
      wazuh:
        ipv4_address: 10.0.1.12
    environment:
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - /data/elastic/es02:/usr/share/elasticsearch/data
      - ./production_cluster/ssl_certs/root-ca.pem:/usr/share/elasticsearch/config/root-ca.pem
      - ./production_cluster/ssl_certs/es02.key:/usr/share/elasticsearch/config/es02.key
      - ./production_cluster/ssl_certs/es02.pem:/usr/share/elasticsearch/config/es02.pem
      - ./production_cluster/ssl_certs/admin.pem:/usr/share/elasticsearch/config/admin.pem
      - ./production_cluster/ssl_certs/admin.key:/usr/share/elasticsearch/config/admin.key
      - ./eproduction_cluster/lastic_conf/es02.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./production_cluster/lastic_conf/internal_users.yml:/usr/share/elasticsearch/plugins/opendistro_security/securityconfig/internal_users.yml

  es03:
    image: amazon/opendistro-for-elasticsearch:1.13.2
    hostname: es03
    container_name: es03
    restart: always
    cpus: 1.0
    mem_limit: 4g
    networks:
      wazuh:
        ipv4_address: 10.0.1.13
    environment:
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - /data/elastic/es03:/usr/share/elasticsearch/data
      - ./production_cluster/ssl_certs/root-ca.pem:/usr/share/elasticsearch/config/root-ca.pem
      - ./production_cluster/ssl_certs/es03.key:/usr/share/elasticsearch/config/es03.key
      - ./production_cluster/ssl_certs/es03.pem:/usr/share/elasticsearch/config/es03.pem
      - ./production_cluster/ssl_certs/admin.pem:/usr/share/elasticsearch/config/admin.pem
      - ./production_cluster/ssl_certs/admin.key:/usr/share/elasticsearch/config/admin.key
      - ./production_cluster/elastic_conf/es03.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./production_cluster/elastic_conf/internal_users.yml:/usr/share/elasticsearch/plugins/opendistro_security/securityconfig/internal_users.yml
  
  es04:
    image: amazon/opendistro-for-elasticsearch:1.13.2
    hostname: es04
    container_name: es04
    restart: always
    cpus: 1.0
    mem_limit: 8g
    networks:
      wazuh:
        ipv4_address: 10.0.1.14
    environment:
      - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - /data/elastic/es04:/usr/share/elasticsearch/data
      - ./production_cluster/ssl_certs/root-ca.pem:/usr/share/elasticsearch/config/root-ca.pem
      - ./production_cluster/ssl_certs/es04.key:/usr/share/elasticsearch/config/es04.key
      - ./production_cluster/ssl_certs/es04.pem:/usr/share/elasticsearch/config/es04.pem
      - ./production_cluster/ssl_certs/admin.pem:/usr/share/elasticsearch/config/admin.pem
      - ./production_cluster/ssl_certs/admin.key:/usr/share/elasticsearch/config/admin.key
      - ./production_cluster/elastic_conf/es04.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./production_cluster/elastic_conf/internal_users.yml:/usr/share/elasticsearch/plugins/opendistro_security/securityconfig/internal_users.yml

  es05:
    image: amazon/opendistro-for-elasticsearch:1.13.2
    hostname: es05
    container_name: es05
    restart: always
    cpus: 1.0
    mem_limit: 8g
    networks:
      wazuh:
        ipv4_address: 10.0.1.15
    environment:
      - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - /data/elastic/es05:/usr/share/elasticsearch/data
      - ./production_cluster/ssl_certs/root-ca.pem:/usr/share/elasticsearch/config/root-ca.pem
      - ./sproduction_cluster/sl_certs/es05.key:/usr/share/elasticsearch/config/es05.key
      - ./production_cluster/ssl_certs/es05.pem:/usr/share/elasticsearch/config/es05.pem
      - ./production_cluster/ssl_certs/admin.pem:/usr/share/elasticsearch/config/admin.pem
      - ./production_cluster/ssl_certs/admin.key:/usr/share/elasticsearch/config/admin.key
      - ./production_cluster/elastic_conf/es05.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./production_cluster/elastic_conf/internal_users.yml:/usr/share/elasticsearch/plugins/opendistro_security/securityconfig/internal_users.yml

  es06:
    image: amazon/opendistro-for-elasticsearch:1.13.2
    hostname: es06
    container_name: es06
    restart: always
    cpus: 1.0
    mem_limit: 8g
    networks:
      wazuh:
        ipv4_address: 10.0.1.16
    environment:
      - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - /data/elastic/es06:/usr/share/elasticsearch/data
      - ./production_cluster/ssl_certs/root-ca.pem:/usr/share/elasticsearch/config/root-ca.pem
      - ./production_cluster/ssl_certs/es06.key:/usr/share/elasticsearch/config/es06.key
      - ./production_cluster/ssl_certs/es06.pem:/usr/share/elasticsearch/config/es06.pem
      - ./production_cluster/ssl_certs/admin.pem:/usr/share/elasticsearch/config/admin.pem
      - ./production_cluster/ssl_certs/admin.key:/usr/share/elasticsearch/config/admin.key
      - ./production_cluster/elastic_conf/es06.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./production_cluster/elastic_conf/internal_users.yml:/usr/share/elasticsearch/plugins/opendistro_security/securityconfig/internal_users.yml
  
  es07:
    image: amazon/opendistro-for-elasticsearch:1.13.2
    hostname: es07
    container_name: es07
    restart: always
    cpus: 1.0
    mem_limit: 4g
    networks:
      wazuh:
        ipv4_address: 10.0.1.17
    environment:
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - /data/elastic/es07:/usr/share/elasticsearch/data
      - ./production_cluster/ssl_certs/root-ca.pem:/usr/share/elasticsearch/config/root-ca.pem
      - ./production_cluster/ssl_certs/es07.key:/usr/share/elasticsearch/config/es07.key
      - ./production_cluster/ssl_certs/es07.pem:/usr/share/elasticsearch/config/es07.pem
      - ./production_cluster/ssl_certs/admin.pem:/usr/share/elasticsearch/config/admin.pem
      - ./production_cluster/ssl_certs/admin.key:/usr/share/elasticsearch/config/admin.key
      - ./production_cluster/elastic_conf/es07.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./production_cluster/elastic_conf/internal_users.yml:/usr/share/elasticsearch/plugins/opendistro_security/securityconfig/internal_users.yml

  kibana:
    image: wazuh/wazuh-kibana-odfe:4.1.5
    hostname: kibana
    container_name: kibana
    restart: always
    cpus: 0.5
    mem_limit: 1g
    networks:
      wazuh:
        ipv4_address: 10.0.1.8
    ports:
      - 5601:5601
    env_file:
      - ".env"
    environment:
      - ELASTICSEARCH_USERNAME=admin
      - ELASTICSEARCH_PASSWORD=$ELASTIC_ADMIN_PASS
      - SERVER_SSL_ENABLED=true
      - SERVER_SSL_CERTIFICATE=/usr/share/kibana/config/cert.pem
      - SERVER_SSL_KEY=/usr/share/kibana/config/key.pem
      - WAZUH_API_URL="https://wazuh"
      - API_USERNAME=wazuh-api
      - API_PASSWORD=$WAZUH_API_PASS
    volumes:
      - ./production_cluster/kibana_ssl/cert.pem:/usr/share/kibana/config/cert.pem
      - ./production_cluster/kibana_ssl/key.pem:/usr/share/kibana/config/key.pem
    depends_on:
      - es01

  nginx:
    image: nginx:stable
    hostname: nginx
    container_name: nginx
    restart: always
    cpus: 0.5
    mem_limit: 512m
    networks:
      wazuh:
        ipv4_address: 10.0.1.7
    ports:
      - "80:80"
      - "443:443"
      #- "1514:1514"
    depends_on:
      - wazuh
      - kibana
    volumes:
      - ./production_cluster/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./production_cluster/nginx/ssl:/etc/nginx/ssl:ro

networks:
  wazuh:
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: 10.0.1.0/24